title: "my corner of delights"
description: "personal writing"
author: Becky
baseurl: ""
url: ""

permalink: /:year/:month/:day/:title/

plugins:
  - jekyll-feed

markdown: kramdown
highlighter: rouge
theme: minima

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
